# File: docker-compose.yml
version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    command: npm run dev
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  selenium-runner:
    build:
      context: ./ui_tests
    depends_on:
      - frontend
    environment:
      - CHROME_BIN=/usr/bin/chromium
      - CHROMEDRIVER=/usr/bin/chromedriver
    volumes:
      - ./ui_tests:/app
    working_dir: /app
    command: pytest test_dashboard.py --maxfail=1 --disable-warnings --tb=short

